clone_depth: 5

configuration:
  - Debug
  - Release

build:
  parallel: true
  project: %APPVEYOR_BUILD_FOLDER%\build\vc12\glewinfo.vcxproj

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\Win32\
  - cmd: type glewinfo.txt